import * as fs from "fs";
import * as path from "path";
import { spawnSync } from "child_process";
import { loadLocalEnv } from "./lib/load-env";

loadLocalEnv();

type ExportShape = {
  exported_at: string;
  tables: Record<string, unknown[]>;
};

const args = process.argv.slice(2);

function getArg(flag: string, fallback?: string) {
  const index = args.indexOf(flag);
  if (index === -1) return fallback;
  return args[index + 1];
}

function hasFlag(flag: string) {
  return args.includes(flag);
}

const INPUT_PATH =
  getArg("--input") || path.resolve(process.cwd(), ".tmp/supabase-export.json");
const OUTPUT_PATH =
  getArg("--output") || path.resolve(process.cwd(), ".tmp/d1-import.sql");
const DATABASE_NAME = getArg("--database") || "motba";
const WRANGLER_ENV = getArg("--env");
const EXECUTE = hasFlag("--execute");
const LOCAL = hasFlag("--local");

const EXPORT = JSON.parse(fs.readFileSync(INPUT_PATH, "utf8")) as ExportShape;

const DELETE_ORDER = [
  "artwork_links",
  "artwork_images",
  "submissions",
  "artworks",
  "artists",
];

const INSERT_ORDER = [
  "artists",
  "artworks",
  "artwork_images",
  "artwork_links",
  "submissions",
];

function sqlLiteral(value: unknown): string {
  if (value === null || value === undefined) return "NULL";
  if (typeof value === "number") return Number.isFinite(value) ? String(value) : "NULL";
  if (typeof value === "boolean") return value ? "1" : "0";
  if (Array.isArray(value) || typeof value === "object") {
    return sqlLiteral(JSON.stringify(value));
  }
  return `'${String(value).replaceAll("'", "''")}'`;
}

function rowToInsert(table: string, row: Record<string, unknown>) {
  const columns = Object.keys(row);
  const values = columns.map((column) => {
    const value = row[column];
    if (column === "is_active" || column === "is_ongoing") {
      return value ? "1" : "0";
    }
    if (column === "gallery_image_ids") {
      return sqlLiteral(
        Array.isArray(value) || typeof value === "object"
          ? JSON.stringify(value ?? [])
          : value ?? "[]"
      );
    }
    return sqlLiteral(value);
  });

  return `INSERT INTO ${table} (${columns.join(", ")}) VALUES (${values.join(", ")});`;
}

function buildSql() {
  const lines: string[] = [
    "-- Generated by scripts/import-d1.ts",
    `-- Exported at ${EXPORT.exported_at}`,
    "PRAGMA foreign_keys = OFF;",
  ];

  for (const table of DELETE_ORDER) {
    lines.push(`DELETE FROM ${table};`);
  }

  for (const table of INSERT_ORDER) {
    const rows = EXPORT.tables[table] || [];
    lines.push(`-- ${table}: ${rows.length} rows`);
    for (const row of rows) {
      lines.push(rowToInsert(table, row as Record<string, unknown>));
    }
  }

  lines.push("PRAGMA foreign_keys = ON;");
  return lines.join("\n");
}

function executeSql() {
  const commandArgs = ["wrangler", "d1", "execute", DATABASE_NAME];

  if (!LOCAL) {
    commandArgs.push("--remote");
  }

  if (WRANGLER_ENV) {
    commandArgs.push("--env", WRANGLER_ENV);
  }

  commandArgs.push("--file", OUTPUT_PATH);

  const result = spawnSync("npx", commandArgs, {
    cwd: process.cwd(),
    stdio: "inherit",
    env: process.env,
  });

  if (result.status !== 0) {
    process.exit(result.status ?? 1);
  }
}

fs.mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true });
fs.writeFileSync(OUTPUT_PATH, buildSql());
console.log(`Import SQL written to ${OUTPUT_PATH}`);

if (EXECUTE) {
  executeSql();
}
